

meta2amsc_dict = {
 "name": "name",
 "owner": "owner",
 "size": "size",
 "datasets": "parent_fQN",
 "updated_by": "updated_by",
 "updated_timestamp": "updated_at",
 "AmSC.common.description": "description",
 "AmSC.common.display_name": "display_name",
 "AmSC.common.domains": "domains",
 "AmSC.common.fqn": "fqn",
 "AmSC.common.location": "location", 
 "AmSC.common.type": "type",
 "AmSC.common.license": "license",
 "AmSC.common.original_source": "original_source",
 "AmSC.common.persistent_identifier": "persistent_identifier",
 "AmSC.common.tags": "tags",
 "AmSC.common.version": "version",
 "AmSC.artifact.format": "format",
 "AmSC.ml_model.service_type": "service_type",
 "AmSC.ml_model.algorithm": "algorithm",
 "AmSC.ml_model.hyperparameters": "hyper_parameters",
 "AmSC.ml_model.storage_location": "storage_location",
 "AmSC.ml_model.features": "features",
 "AmSC.ml_model.target_variable": "target_variable",
 "AmSC.ml_model.server_endpoint": "server_endpoint",
 "AmSC.ml_model.dashboard": "dashboard",
 "AmSC.ml_model.model_version": "model_version",
 "AmSC.ml_model.extension": "extension",
 "AmSC.table.columns": "columns",
 "AmSC.table.table_type": "table_type",
 "AmSC.table.service_type": "service_type",
 "AmSC.reference.reference_type": "reference_type",
 "AmSC.reference.relationship_type": "relationship_type",
 "AmSC.reference.source_entity": "source_entity",
 "AmSC.reference.target_URI", "target_URI",
}

amsc2meta_dict = { v: k for k,v in meta2amsc_dict.items() }
