#!/usr/bin/env python
import argparse
import configparser
from metacat2amsc.convert import convert, AmSCClient
import fcntl

import logging

logger = logging.getLogger(__name__)

class FileLock:
    def __init__(self, filename, lock_type=fcntl.LOCK_EX):
        self.fh = None
        if filename:
            self.fh = open(filename, "a")
            self.lock_type = lock_type

    def __enter__(self):
        if self.fh:
            fcntl.flock(self.fh.fileno(), self.lock_type)

    def __exit__(self, type, value, tb):
        if self.fh:
            fcntl.flock(self.fh.fileno(), fcntl.LOCK_UN)
            self.fh.close()


def main():
    p = argparse.ArgumentParser()
    p.add_argument("-c", help="Config file", default="migrator.ini")
    p.add_argument("-d", help="Debugging on", default=False, action="store_true")
    p.add_argument("-q", help="Query instead")
    p.add_argument("-g", help="GET catalog fqn instead")
    p.add_argument("-D", help="DELETE catalog fqn instead")

    level = logging.INFO
    args = p.parse_args()
    if args.d:
        level = logging.DEBUG

    config = configparser.ConfigParser()
    config.read(args.c)
    if config.get("general", "debug", fallback=False):
        level = logging.DEBUG

    logging.basicConfig(level=level)
    logging.debug("migrator: starting...")

    if args.q:
        c = AmSCClient(config)
        res = c.query(args.q)
        print(f"Query Result: {repr(res)}")
        exit(0)
    if args.g:
        c = AmSCClient(config)
        res = c.get(args.g)
        print(f"Get Result: {repr(res)}")
        exit(0)
    if args.D:
        c = AmSCClient(config)
        res = c.delete_item(args.D)
        print(f"DELETE Result: {repr(res)}")
        exit(0)

    lf = config.get("general", "lock_file",fallback="")
    with FileLock(lf):
        convert(config)


if __name__ == "__main__":
    main()
