#!/usr/bin/env python
import argparse
import configparser
from metacat2amsc.convert import convert, AmSCClient

import logging

logger = logging.getLogger(__name__)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("-c", help="Config file", default="migrator.ini")
    p.add_argument("-d", help="Debugging on", default=False, action="store_true")
    p.add_argument("-q", help="Query instead")
    p.add_argument("-g", help="GET catalog fqn instead")
    p.add_argument("-D", help="DELETE catalog fqn instead")

    level = logging.INFO
    args = p.parse_args()
    if args.d:
        level = logging.DEBUG

    config = configparser.ConfigParser()
    config.read(args.c)
    if config.get("general", "debug", fallback=False):
        level = logging.DEBUG

    logging.basicConfig(level=level)

    if args.q:
        c = AmSCClient(config)
        res = c.query(args.q)
        print(f"Query Result: {repr(res)}")
        exit(0)
    if args.g:
        c = AmSCClient(config)
        res = c.get(args.g)
        print(f"Get Result: {repr(res)}")
        exit(0)
    if args.D:
        c = AmSCClient(config)
        res = c.delete_item(args.D)
        print(f"DELETE Result: {repr(res)}")
        exit(0)

    convert(config)


if __name__ == "__main__":
    main()
